node_lines:
- node_line_name: retrieve_node_line
  nodes:
  - modules:
    - embedding_model: huggingface_all_mpnet_base_v2
      module_type: vectordb
    node_type: retrieval
    strategy:
      metrics:
      - retrieval_f1
      - retrieval_recall
      - retrieval_precision
    top_k: 3
- node_line_name: post_retrieve_node_line
  nodes:
  - modules:
    - module_type: fstring
      prompt: "Read the passages and answer the given question. \n Question: {query}\
        \ \n Passage: {retrieved_contents} \n Answer : "
    node_type: prompt_maker
    strategy:
      metrics:
      - meteor
      - rouge
      - bert_score
  - modules:
    - llm: bedrock
      model: amazon.titan-text-express-v1
      module_type: llama_index_llm
      profile_name: autorag-martin
    node_type: generator
    strategy:
      metrics:
      - meteor
      - rouge
      - bert_score
